### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/cinema#1]
## 📝 개요

전체 코드 리팩토링

## ✅ TODO
- [ ] ESLint 규칙 수정 및 적용
- [x] api 폴더 구조 변경
- [ ] 컴포넌트 구조 및 로직 수정
- [ ] 캐시 설정 변경
